---
architecture: arm64
chroma_release: 0.9.4

pip3_path: /usr/local/opt/python/bin/pip3
gopath: "{{ ansible_env.HOME }}/go"
ssh_key_path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

email: dev@artis3nal.com
handle: Artis3n

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_dock: false

homebrew_installed_packages:
  - act
  - adr-tools
  - asciinema
  - awscli
  - bash-completion
  - bats-core
  - conftest
  - dive
  - gcc
  - gettext
  - gh
  - git
  - git-lfs
  - gnu-tar
  - gnupg
  - go
  - hadolint
  - hashicorp/tap/boundary
  - helm
  - jq
  - kubectl
  - magic-wormhole
  - make
  - mas
  - minisign
  - mkcert
  - nodejs
  - nomad
  - npm
  - opa
  - packer
  - plantuml
  - preflight
  - pre-commit
  - python
  - p7zip
  - superfly/tap/flyctl
  - readline
  - terraform
  - terraform-docs
  - tmux
  - vault
  - waypoint
  - wget

homebrew_taps:
  - github/gh
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - spectralops/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aws-vault
  - docker
  - dropbox
  - font-hack
  - font-jetbrains-mono
  - firefox
  - hashicorp/tap/hashicorp-boundary-desktop
  - iterm2
  - jetbrains-toolbox
  - parallels
  - parallels-virtualization-sdk
  - rectangle
  - secretive
  - session-manager-plugin
  - snagit
  - temurin
  - visual-studio-code
  - zoom

mas_installed_apps:
  - 1085114709  # Parallels Desktop
  - 803453959  # Slack
  - 1475387142  # Tailscale
  - 1327661892  # Xmind
mas_email: ""
mas_password: ""

zsh_custom_plugins:
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: zsh-syntax-highlighting
    version: master
  - repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: zsh-autosuggestions
    version: master

git_global_configs:
  - name: user.email
    value: '{{ email }}'
  - name: user.name
    value: '{{ handle }}'
  - name: push.default
    value: simple
  - name: alias.ci
    value: commit
  - name: alias.s
    value: status
  - name: alias.br
    value: branch
  - name: alias.co
    value: checkout
  - name: alias.get
    value: pull --prune
  - name: alias.list
    value: config --get-regexp alias
  - name: alias.save
    value: stash save
  - name: init.defaultBranch
    value: main
  - name: pull.rebase
    value: 'false'
  - name: alias.a
    value: "add ."

npm_global_packages:
  - pnpm
  - yarn

pip_global_packages:
  - pipenv
