---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_dock: false

homebrew_installed_packages:
  - git
  - github/gh/gh
  - go
  - node
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - dropbox
  - firefox
  - slack

mas_installed_apps: []
mas_email: ""
mas_password: ""
