---
ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
architecture: arm64

email: dev@artis3nal.com
handle: Artis3n

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_dock: false

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - gettext
  - git
  - github/gh/gh
  - go
  - node
  - readline
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - dropbox
  - firefox
  - slack

mas_installed_apps: []
mas_email: ""
mas_password: ""

zsh_custom_plugins:
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: 'zsh-syntax-highlighting'
  - repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: 'zsh-autosuggestions'

git_global_configs:
  - name: user.email
    value: '{{ email }}'
  - name: user.name
    value: '{{ handle }}'
  - name: push.default
    value: simple
  - name: alias.ci
    value: commit
  - name: alias.s
    value: status
  - name: alias.br
    value: branch
  - name: alias.co
    value: checkout
  - name: alias.get
    value: pull --prune
  - name: alias.list
    value: config --get-regexp alias
  - name: alias.save
    value: stash save
  - name: init.defaultBranch
    value: main
  - name: pull.rebase
    value: 'false'

npm_global_packages:
  - pnpm
  - yarn

pip_packages:
  - pre-commit
