---
- name: Dependencies | Install Global Pip 2 Packages
  ansible.builtin.pip:
    name: "{{ pip2_global_packages }}"
    state: present
    extra_args: --user

- name: Dependencies | Install Global Pip 3 Packages
  ansible.builtin.pip:
    name: "{{ pip_global_packages }}"
    state: present
    executable: "{{ pip3_path }}"

- name: Dependencies | Install Global NPM Packages
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
  loop: "{{ npm_global_packages }}"
