---
- name: Git | Set Global Config
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: '{{ git_global_configs }}'

- name: Git | Configure SSH Key
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    create: true
    owner: "{{ ansible_env.USER }}"
    group: "staff"
    mode: 0600
    block: |
      Host github
        HostName github.com
        IdentityFile {{ new_ssh_key.filename | default(ssh_key_path) }}
