---
- name: Git | Install Packages
  community.general.homebrew:
    name: '{{ git_brew_packages }}'
    state: present

- name: Git | Install LFS  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: git lfs install
  changed_when: false

- name: Git | Set Global Config
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: '{{ git_global_configs }}'

- name: Git | Configure SSH Key
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    block: |
      Host github
        HostName github.com
        IdentityFile {{ new_ssh_key.filename | default(ssh_key_path) }}
