---
- name: SSH | Check For Completion
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ansible_ssh"
  register: ssh_completed_check

- name: SSH | Setup SSH Keys
  when: not ssh_completed_check.stat.exists
  tags: notest
  block:
    - name: SSH | Setup Secretive
      ansible.builtin.pause:
        prompt: |
          Open the Secretive App and follow its instructions.

          Then press enter to continue.

    - name: SSH | Create SSH Keys - {{ item }}
      ansible.builtin.pause:
        prompt: |
          Create a Secretive SSH key and enter the Public Key Path for the key - "{{ item }}"
      loop: "{{ ssh_keys }}"
      register: pubkeys

    - name: SSH | Validate Public Key Inputs  # noqa empty-string-compare
      ansible.builtin.fail:
        msg: "{{ item.item }} SSH key was empty!"
      when: item.user_input == ""
      loop: "{{ pubkeys.results | from_yaml | list }}"

    - name: SSH | SSH Config
      ansible.builtin.template:
        src: ../files/sshconfig.j2
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        owner: "{{ ansible_env.USER }}"
        group: "staff"
        mode: '0644'
        backup: true
      notify: SSH Idempotency
