---
- name: Terminal | Install Oh My ZSH
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/oh-my-zsh.sh"

- name: Terminal | ZSH Spaceship Theme
  ansible.builtin.git:
    repo: "https://github.com/spaceship-prompt/spaceship-prompt"
    version: master
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt"
  register: spaceship_repo

- name: Terminal | Add Custom Plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    version: "{{ item.version }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.dest }}"
  loop: "{{ zsh_custom_plugins }}"

- name: Terminal | ZSH Spaceship Symbolic Link
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
    owner: "{{ ansible_env.USER }}"
    group: "staff"

- name: Terminal | Update Shell Profile
  ansible.builtin.template:
    src: ../files/.zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "staff"
    mode: 0644
    backup: true

- name: Terminal | Install Platform Tools
  ansible.builtin.unarchive:
    src: https://dl.google.com/android/repository/platform-tools-latest-darwin.zip
    dest: "{{ ansible_env.HOME }}/Documents/"
    remote_src: true
