---
name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4.7.0
        id: setup-python
        with:
          python-version: '3.10'

      - name: Install dependency manager
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint code
        run: make lint

  integration:
    name: Integration
    runs-on: macos-latest
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4.7.0
        id: setup-python
        with:
          python-version: '3.10'

      - name: Uninstall pre-packaged browsers
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app

      - name: Install dependency manager
        run: pip install poetry

      - name: Install test dependencies
        run: poetry install --no-interaction --no-dev

      - name: Setup test environment
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory ./inventory
          cp tests/config.yml ./config.yml
          poetry run ansible-galaxy install -r requirements.yml

      - name: Test playbook syntax
        run: poetry run ansible-playbook main.yml --syntax-check

      - name: Test the playbook.
        run: poetry run ansible-playbook main.yml --skip-tags notest
        env:
          # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          poetry run ansible-playbook main.yml --skip-tags notest | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
